vexip-ui/vexip-ui

- common/config/src/index.ts
- common/config/src/z-index.ts
- components/create.ts
- components/popup/popup-item.vue
- components/popup/popup.vue
- components/popup/symbol.ts
- style/masker.scss
- style/popup.scss
- style/spin.scss
> feat(config): add global z-index config

- components/viewer/viewer.vue
> feat: add zoom range

- common/config/src/locale/en-US.ts
- common/config/src/locale/helper.ts
- common/config/src/locale/zh-CN.ts
- components/viewer/symbol.ts
- components/viewer/viewer.vue
> feat(Viewer): add mirror flip function

- components/icon/icon.tsx
- 删除不必要的 `else if`
- 优先顺序：`slot` > `icon` > `name`。
> refactor(component): simplify `<Icon>` conditional statements

- docs/i18n/en-US.ts
- docs/i18n/helper.ts
- docs/i18n/zh-CN.ts
- docs/views/homepage.vue
参考多数组件库做法，不会直接跳转到组件界面，而是从介绍、安装和使用开始。
> docs: adjust the entry buttons target

- docs/demos/slider/api.en-US.md
- docs/demos/slider/api.zh-CN.md
> docs(component): add disabled description for silider

- docs/demos/slider/api.en-US.md
- docs/demos/slider/api.zh-CN.md
同时根据 `props` 书写顺序，调整 `disabled` 位置。
> docs(component): add state description for slider

- README.md
- README.zh-CN.md
> chore: readme MIT path error

- docs/demos/checkbox/api.en-US.md
- docs/demos/checkbox/api.zh-CN.md
> docs: ✏️ add state description for `Checkbox`

- README.md
- README.zh-CN.md
- docs/guides/setup/desc.en-US.md
- docs/guides/setup/desc.zh-CN.md
> chore: 🤖 make the image clickable

- README.md
- README.zh-CN.md
- docs/guides/setup/desc.en-US.md
- docs/guides/setup/desc.zh-CN.md
> chore: 🤖 updated the installation mode

- playground/app.vue
Just change the spelling of a word.
> chore: update playground app.use word spelling

- components/radio/radio.vue
https://playground.vexipui.com/#eNqVVd2O20QUfpWRi2pHSuwbrqIkWkAIuENb7uoqdeOT9XTtGTMeJ63SlZaCSvdPFUIqUlUhuOGqCCFEN1uy5WWS7HK1r8CZGcdx0u6qlXYzM+d85zu/Mx5ZH6WpO8jBalotCUkaBxI6PiOklXZm+7+cn55Ox79Px0ezJ3+cTZ6ev/7hYvKs5aUGshmElH8meJ6SZszxwLbavlXsfIsUu0bMe9ukyVNJOcsQUex8q9PylhwLt2ohpHSODo2kdWNIZS8ig0bCQ4ibgyDOoeoP2QzEMC2ivCNW1+jDzvzHo+npc50KnrSUx4XjVkw7BSW5fn01h7P9l/Pdb6bjg4vJ4dnDk9n3/0zHu/MXvwqVxMXk8fT1wey3h0YzO/xp+urFxWSv5SHjknv25On85eOCdl336AjZCuaTg9ne0dmz7xZEh9iG829P/9vdUy159ai0bXk6+JZXaSAes56gqSQZSOxPHOjeSFV0n9Ek5UKSERHQJzukL3hCbJwCWxn2sDVykTdpK4wjRQ61hapoH6pu2iY4u07s6Xh//vex2s1O/p0d/6x28+M/Z8//sm+p4Ew46NyqW8Z/5t7NOMPJG6ks/IXUt5pktOMz/CuhjSRIr0CbCvoWpqDOvhVJmWZNz8tZur3l9njioWpD1SaTXkjxB8+uyJmkCbiQJY07gg8zEOjEt+oVPg+FAxANASwEAeIy/o23YFccrumucAr3aNrI6aWZFPrVdAqhm7yVy8vk/RjcXqbr9c6sFauScqPkpGoc …
> fix: when you click on radio in loading-lock, it will be selected

- components/layout/helper.ts
- components/layout/layout-aside.tsx
- components/layout/layout-header.tsx
- components/layout/layout.tsx
- components/layout/symbol.ts
- components/native-scroll/native-scroll.tsx
- components/native-scroll/symbol.ts
- dev-server/app.vue
- docs/demos/layout/api.en-US.md
- docs/demos/layout/api.zh-CN.md
- style/layout.scss
> refactor(Layout): adjust structure of elements for more concise

- common/config/src/locale/index.ts
- common/config/src/locale/ta-IN.ts
Locale added for Indian Tamil language.
> Tamil language added

- common/config/src/locale/index.ts
- components/create.ts
- components/index.ts
- docs/common/header.vue
- docs/guides/global/desc.en-US.md
- docs/guides/global/desc.zh-CN.md
- docs/i18n/index.ts
- docs/tsconfig.json
- docs/vite.config.ts
- full-lib.ts
- index.ts
- package.json
- scripts/bootstrap.ts
- tsconfig.json
- vite.full.config.ts
> refactor(config): external locale config for on demand import

- CONTRIBUTING.md
- package.json
- pnpm-lock.yaml
> chore: update pnpm version

- package.json
remove excess whitespace in package.json
> style: remove excess whitespace

- components/auto-complete/auto-complete.vue
fix auto-complate component ignoreCase prop disworking
> fix(auto-complate): miss ignoreCase prop

- common/meta/package.json
remove meta package spare script copy-dist
> chore: remove spare script copy-dist

- components/table/store.ts
- components/table/symbol.ts
- components/table/table-column.ts
- docs/demos/table/api.en-US.md
- docs/demos/table/api.zh-CN.md
> fix: table defineColumns type error

- common/config/src/props.ts
useProps should exec validator function at once.
> fix(useProps): exec validator at once

- scripts/utils.ts
Using serve there has 70+ components, It's better to auto complete by user input.
Not issue
> feat(serve): support serve auto complete

- package.json
> chore: remove useless scripts

- common/plugins/src/unplugin-vue-components.ts
> chore: adjust meta data path

- docs/vite.config.ts
add optimizeDeps include @vexip-ui/icons
> fix: add optimizeDeps include @vexip-ui/icons

- playground/components/header.vue
> chore(playground): optimize vue version fetch

- common/config/src/props.ts
- common/utils/src/event-emitter.ts
- components/masker/masker.vue
1. fix typo (`vaild` -> `valid`)
2. fix typo (`playload` -> `payload`)
> docs: fix typo

- .github/workflows/ci.yml
https://docs.github.com/en/actions/using-jobs/using-concurrency
> chore: cancel same in-progress workflow

- common/meta/scripts/components.ts
- common/meta/scripts/contributors.ts
> style(meta): eslint style adjust

- common/utils/src/date.ts
- components/date-picker/date-picker.vue
releated #339
incorrect leap year function name
> fix(date-picker): incorrect leap year function name

- components/timeline/index.ts
- components/timeline/props.ts
- components/timeline/symbol.ts
- components/timeline/timeline-item.vue
releated https://github.com/vexip-ui/vexip-ui/pull/339
incorrect TimelineItem type
> fix(timeline): incorrect TimelineItem type

- components/tooltip/index.ts
- components/tooltip/props.ts
- components/tooltip/symbol.ts
> types(tooltip): incorrect TooltipTrigger type

- CONTRIBUTING.md
- common/meta/scripts/contributors.ts
- docs/en-US/guide/development-guide.md
- docs/zh-CN/guide/development-guide.md
- playground/store.ts
- scripts/release.ts
- scripts/test-setup.ts
> chore: fix internal typos

- components/confirm/tests/confirm.spec.tsx
- components/contextmenu/tests/contextmenu.spec.tsx
- components/full-screen/tests/fullScreen.spec.tsx
- components/layout/tests/layout.spec.tsx
- components/transfer/tests/transfer.spec.tsx
> test(all): fix typos

- components/form/validator.ts
- docs/en-US/component/form.md
- docs/zh-CN/component/form.md
incorrect ValidatorResult type
> types(form): incorrect ValidatorResult type

- components/input/props.ts
- components/table/table.vue
> chore: fix typo in code

- components/menu/symbol.ts
incorrect toggleGroupExpanded argument type
> types(menu): incorrect toggleGroupExpanded argument type

- style/avatar.scss
- style/badge.scss
- style/breadcrumb.scss
- style/bubble.scss
- style/button.scss
- style/shared/mixins.scss
> feat: rtl (wip)

- docs/.vitepress/theme/components/doc-search.vue
optimize mobile search display
> docs: optimize mobile search display

- components/table/table-head-cell.vue
> chore(table-head-cell): remove useless console

- style/input.scss
incorrect count-color-disabled variable
> chore(input): incorrect count-color-disabled variable

- style/image.scss
> chore(image): incorrect handler mixins name

- style/anchor.scss
> fix(anchor): incorrect track-color-active variable

- style/time-picker.scss
> chore(time-picker): incorrect enabled class name

- docs/en-US/guide/getting-started.md
- docs/zh-CN/guide/getting-started.md
I think the direct import method shown in the documentation is incomplete enough, So I revised this part of the documentation.
(still need to manually add a mount method when I copy the document directly to use)
> docs: update getting-start.md

- docs/.vitepress/config.ts
- docs/.vitepress/theme/index.ts
add og meta and description meta to improve seo
en-US
zh-CN
dynamic og:title
> docs: add og meta to improve SMO and SEO

- components/confirm/confirm.vue
- components/confirm/props.ts
- components/confirm/symbol.ts
- docs/demos/confirm/type/demo.en-US.vue
- docs/demos/confirm/type/demo.zh-CN.vue
- docs/en-US/component/confirm.md
- docs/zh-CN/component/confirm.md
feat(confirm): add cancelType prop
> feat(confirm): add cancelType prop

- .husky/post-merge
- .husky/post-rebase
- .husky/scripts/update-dep
add git hooks when lock file change it will run pnpm install after merge
just like this:
> chore: add git hooks

- components/checkbox/checkbox.vue
- components/radio/radio.vue
- components/switch/switch.vue
select event will  triggered twice
[look here](https://playground.vexipui.com/#eNqlVNtu20YQ/ZUFXYQUoJAo8mZIQmrXQFK4F9h+CwOGJUfi2stddnepC2QBeTXSok9960v/wu33pEXzF51ZXkQJbVqggAAtZ87MnJk5u1vP6Cz6rKrCZQ3eqTexUFYitTCLJWOTz7WqcrWS7LkBAZmdxl5ziD0HQMhZba2SzG4qQG+leZnqTe9m7P3juz/ePfz548+///BTGxI1MV2GriQ7ybFcH9gXv+TG9taB/SUGMpmWVPfD24cPv/z6/vHtoLIDnxeQ3X2r1rMG8ekk6i2DlNEw53+s9dv3x7WuV9xmxWwStYf/WeDx4bjAVZpz1XaC7knUGP61zt48mOUkOtx1j8HPA9/EZJpXlhmwdcVEKhfI0RpHLlPSkIc0waYsgBGbztiWEpJLCQiFWqA5ljtK26TCQG/s8bJS2j4t0yq8NUqi+lxc3DqwwCnbYhT+EG0NJpzzxRE2U2XFBeivK8uxoItp+ou9VAi1+sLZrK5h3NkzUsDf2G/NmmykYjCglxB7vc+megEoe3JfXH8Fazz3zlLltUD0R5xXgMOoiWMDO6tljrQHOMf2pWudy8WNuVhbkKZr6oAoXTZnfRV7S1jz6mnNI2cM85AG95qQO4dHRA3nH5nSvrNn4TMX142cnoYy5RJT4sCbrbAtyzSgMPDNGLOC7dhcq5L5WMSPZSx7FEdhYEt7QMsTUS0GM7S+sHuB9s6bAkpo7lEPG …
> fix(radio checkbox switch): fix click event triggered twice

- components/menu/menu-group.tsx
> chore: remove duplicate code

- components/pagination/pagination.tsx
> fix(pagination): after setting the number of paging items, the selected state is lost

- common/config/src/locale/ar-EG.ts
- common/config/src/locale/de-DE.ts
- common/config/src/locale/en-US.ts
- common/config/src/locale/fr-FR.ts
- common/config/src/locale/helper.ts
- common/config/src/locale/ta-IN.ts
- common/config/src/locale/zh-CN.ts
- common/config/src/locale/zh-HK.ts
- common/config/src/locale/zh-TW.ts
- components/auto-complete/auto-complete.vue
- components/auto-complete/tests/auto-complete.spec.tsx
- components/form/helper.ts
- components/input/input.tsx
- components/input/symbol.ts
- components/select/index.ts
- components/select/props.ts
- components/select/select.tsx
- components/select/symbol.ts
- docs/demos/select/filter-position/demo.en-US.vue
- docs/demos/select/filter-position/demo.zh-CN.vue
- docs/demos/select/filter/demo.zh-CN.vue
- style/select.scss
> feat(select): support customize filter input position

- .vscode/extensions.json
- common/config/src/locale/fa-IR.ts
- common/config/src/locale/index.ts
- docs/en-US/guide/i18n.md
- docs/zh-CN/guide/i18n.md
- index.ts
add persian or farsi translations according to [vexip guides](https://www.vexipui.com/en-US/guide/i18n.html#adding-language) for latest version available today 2.3.14
> add persian (farsi) locale as fa-IR

- components/input/input.tsx
correctly emit compositionend event
> fix(input): correctly emit compositionend event

- style/card.scss
support Card customize header padding css variables
> feat(card): support customize header padding css variables
